### ISSUE TITLE
caler date tournage vieux mans (musée zarbi de l'étrange)

### ISSUE THREAD

**Issue by saladinbhopalgurke** [AMMD/LesNouvellesAventuresDesBaronsFreaks#12]

**Comment by saladinbhopalgurke** [comment]
A mon avis ça sert pas à grand chose de demander une autorisation, sauf 
si on a l'intention de bloquer une/ plusieurs rues... mais je crois que 
c'est pas le délire!


Le 18/10/2021 à 12:44, Aurélien Roux a écrit :

**Comment by orlammd** [comment]
OK, ça veut donc aussi dire autonomie énergétique, donc lumière naturelle (ou phare de bagnole).

**Comment by orlammd** [comment]
Wowow, non, j'avais pas pensé à ça, mais maintenant que tu le dis, ambiance Gotham, ça serait mortel.
Par contre, pour avoir vu que ça donne avec Plagiat, éclairage public = pas assez. Pour autant, Guillaume a des spots sur batterie, faudrait essayer. Je vois ça.

**Comment by orlammd** [comment]
option pour 6 et 13 décembre en + de tournage Vieux Mans
