### ISSUE TITLE
valider les conduites master actes 4-7

### ISSUE THREAD

**Issue by saladinbhopalgurke** [AMMD/LesNouvellesAventuresDesBaronsFreaks#16]

**Comment by orlammd** [comment]
Est-ce que tu pourrais les exporter en pdf ? Quand je les ouvre dans LibreOffice, j'ai des résultats vraiment surprenants, je ne sais pas trop si c'est normal. Merci.

**Comment by orlammd** [comment]
On se cale un mumble + IRC la semaine prochaine ? Suis dispo Lundi toute 
la journée et Mercredi matin, ou sinon en soirée (pas le Mardi).

Le 19/10/2021 à 11:32, saladinbhopalgurke a écrit :

**Comment by saladinbhopalgurke** [comment]
Lundi c'est possible, Pierre Charrier est censé passer faire une 
zinguerie, mais c'est un grand garçon hein!

Par contre si je regarde les agendas auxquels j'ai accès, la prochaine 
date dispo c'est plutôt le lundi d'après..? Il en dit quoi Sassier?

(moi le soir c'est pas possible)


Le 04/11/2021 à 08:29, ORL - AMMD a écrit :

**Comment by SouvPonk** [comment]
hello,
alors, pas dispo lundi, mardi et mercredi. 
mais ok pour jeudi et vendredi, ou lundi et mardi de la semaine d’après.
plutôt en journée.

**Comment by orlammd** [comment]
Lundi ou mardi semaine d'après, alors, car je suis pris jeudi et vendredi.

Le 06/11/2021 à 14:40, SouvPonk a écrit :

**Comment by saladinbhopalgurke** [comment]
Ja. Lundi matin?

Le 07/11/2021 à 18:26, ORL - AMMD a écrit :

**Comment by saladinbhopalgurke** [comment]
Donc lundi matin, ça vous va?


Le 07/11/2021 à 18:26, ORL - AMMD a écrit :

**Comment by orlammd** [comment]
oui, ça roule pour moi.
Pour info, j'ai des GUSO pour Jérémy à signer et récupérer s'il vous 
venait l'idée de faire ça physiquement.

Le 10/11/2021 à 13:48, saladinbhopalgurke a écrit :

**Comment by saladinbhopalgurke** [comment]
Ben plutôt mardi ça l'arrangerait peut-être, la veille de taffer dans 
l'Orne? (c'est bon pour moi aussi)

Mais sinon, un coup de courrier, et puis hop!

Le 10/11/2021 à 13:52, ORL - AMMD a écrit :

**Comment by orlammd** [comment]
Est-ce qu'on peut dire que c'est désormais validé ? (et clore cette issue ?)

**Comment by saladinbhopalgurke** [comment]
Wa l'aut il veut clore des issues hein

Jeudi midi on devrait être pas mal non?

Le 30/11/2021 à 16:16, ORL - AMMD a écrit :
