### ISSUE TITLE
Essayer intégration plateau Isère dans Epidaure

### ISSUE THREAD

**Issue by orlammd** [AMMD/LesNouvellesAventuresDesBaronsFreaks#58]
A faire dès que possible :
- filmer plateau Epidaure,
- filmer Isère (par Dagz) en mode boîte noîre,
- tenter l'intégration.

**Comment by orlammd** [comment]
J'ai fait un premier essai (fichier essaiTheatre.mp4 dans le cloud -> baronsfreaks -> 2020_Creation_Nouvelle
Ca marche pas trop mal, à mon avis, on peut valider le principe sachant que :
- j'ai pas fait de rotoscopie sur l'image de cordes, juste du rognage, donc bien crado,
- l'angle de vue des cordes est un peu contreplongée et filme haut, alors que l'image du plateau que j'avais est un peu plongée et filme le sol.

Note : pour les scènes de trapèze, il faudra au sol un matelas, avec un taps noir, on devrait pouvoir s'en sortir, mais il y aura peut-être un truc à trouver. Le sol dans l'Isère est en béton gris, pas en parquet -> prévoir un parquet d'1 ou 2m² ?

**Comment by saladinbhopalgurke** [comment]
Oh oui ça m'inquiétait pas trop.

J'ai quand même souvenir qu'on s'était dit qu'on ferait le cabaret des 
Vanupiés à Chaoué, mais Epidaure c'est très bien, bien plus facile 
d'accès à mon avis.


Le 01/12/2021 à 10:50, ORL - AMMD a écrit :

**Comment by orlammd** [comment]
Ca fonctionne, à confirmer à Pommier
